name: Deploy to EC2

on:
  push:
    branches: [lambda]

env:
  STAGE: "dev"
  LAMBDA_FUNCTION_NAME: "ci-lambda"
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          echo "installing dependencies from requirements.txt"
          # pip install awscli pytest

      - name: Run unit tests
        run: |
          echo "run python unit tests"
          # python -m unittest discover -s . -p ‘test_*.py’

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Zip the Lambda function
        run: zip function.zip lambda_function.py

      - name: Update Lambda function
        run: |
          echo "Updating Lambda function..."
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://function.zip --publish

      - name: Clean up
        run: rm function.zip
