name: Deploy to EC2

on:
  push:
    branches: [nodejs]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "Setup Node.js"
          echo "$PRIVATE_KEY" > github-ec2.pem && chmod 400 github-ec2.pem
          ssh -o StrictHostKeyChecking=no -i github-ec2.pem ${USER}@${HOST} '
          if ! command -v nvm &> /dev/null; then
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          fi
          nvm install node

          echo "Setup PM2"
          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi

          REPO_URL="https://github.com/zrierc/test.git"
          BRANCH="nodejs"
          REPO_DIR="$HOME/nodejs-app"

          echo "Setup Directory"
          if [ -d "$REPO_DIR" ]; then
            mkdir -p "$REPO_DIR"
          fi

          if [ -d "$REPO_DIR/.git" ]; then
            cd "$REPO_DIR"
            git pull origin "$BRANCH"
          else
            git clone "$REPO_URL" "$REPO_DIR"
            cd "$REPO_DIR"
          fi

          cd "$REPO_DIR/test"
          npm install

          cd "$REPO_DIR/test"
          git pull origin $BRANCH
          npm install

          echo "Starting/restarting application..."
          pm2 restart server.js || pm2 start server.js
          '
